import { HydratedDocument, Types } from 'mongoose';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';

export type CheckinDocument = HydratedDocument<Checkin>;

@Schema({ _id: false })
export class CheckinLocation {
  @Prop({ type: String })
  description?: string;

  @Prop({ type: Number })
  latitude?: number;

  @Prop({ type: Number })
  longitude?: number;
}

@Schema({ timestamps: true })
export class Checkin {
  // User who checked in
  @Prop({ type: Types.ObjectId, ref: 'User', required: true, index: true })
  user: Types.ObjectId;

  // Activity related to this checkin
  @Prop({ type: Types.ObjectId, ref: 'Activity', required: true, index: true })
  activity: Types.ObjectId;

  // Checkin timestamp - when the scan actually happened
  @Prop({ type: Date, default: Date.now, index: true })
  scanTime: Date;

  // Server processing timestamp - when the scan was processed by the server
  @Prop({ type: Date, index: true })
  processedTime: Date;

  // Status of the checkin
  @Prop({
    type: String,
    enum: ['pending', 'success', 'failed', 'duplicate'],
    default: 'pending',
    index: true,
  })
  status: string;

  // Boolean to indicate successful check-in
  @Prop({ type: Boolean, default: false, index: true })
  isCheckedIn: boolean;

  // Additional notes
  @Prop({ type: String })
  notes?: string;

  // Checkin location data
  @Prop({ type: CheckinLocation })
  location?: CheckinLocation;

  // Staff who processed this checkin
  @Prop({ type: Types.ObjectId, ref: 'User' })
  scannedBy: Types.ObjectId;

  // Device ID for offline support
  @Prop({ type: String, index: true })
  deviceId?: string;

  // Local ID generated by the scanner device (used for offline sync)
  @Prop({ type: String })
  localId?: string;

  // Flag to indicate if this was processed offline and synced later
  @Prop({ type: Boolean, default: false })
  isOfflineSync: boolean;

  // Custom fields for flexibility
  @Prop({ type: Object, default: {} })
  metadata: Record<string, any>;
}

export const CheckinSchema = SchemaFactory.createForClass(Checkin);

// Create indexes for better query performance
CheckinSchema.index({ user: 1, activity: 1 }, { unique: true });
CheckinSchema.index({ activity: 1, status: 1 });
CheckinSchema.index({ scanTime: -1 });
CheckinSchema.index({ isCheckedIn: 1 });
CheckinSchema.index({ isOfflineSync: 1 });
CheckinSchema.index({ deviceId: 1, localId: 1 }, { sparse: true });
