apiVersion: v1
kind: Service
metadata:
  name: hllc2025-backend-chat-service # <<--- ชื่อ Service ต้องตรงกับที่ Ingress ชี้ไป
  labels:
    app: hllc2025-backend-chat            # Label สำหรับ Service
spec:
  selector:
    app: hllc2025-backend-chat # <<--- ต้องตรงกับ 'app' label ใน Deployment ของ Go Chat
  ports:
    - protocol: TCP
      port: 80 # <<--- พอร์ตที่ Ingress จะใช้เชื่อมต่อกับ Service นี้ (ใน Cluster)
      targetPort: 8080 # <<--- ต้องตรงกับ containerPort ใน Go Chat Deployment (8080)
  type: ClusterIP # Service ชนิด ClusterIP จะเข้าถึงได้จากภายใน Cluster เท่านั้น
