# k8s/infrastructure/kafka-k8s.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1 # สำหรับการทดสอบ Kafka ต้องการอย่างน้อย 3 สำหรับ HA
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka-container
        image: confluentinc/cp-kafka:7.4.0
        ports:
        - containerPort: 9092 # สำหรับ PLAINTEXT Listener (Clients outside Cluster - if exposed)
          name: plaintext
        - containerPort: 29092 # สำหรับ PLAINTEXT_INTERNAL Listener (Internal Cluster communication)
          name: plaintext-internal
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181" # <<--- ชี้ไปที่ Zookeeper Service
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-service:9092,PLAINTEXT_INTERNAL://kafka-service:29092" # <<--- ชี้ไปที่ Kafka Service
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT_INTERNAL"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        readinessProbe: # Healthcheck สำหรับ Kafka
          exec:
            command: ["bash", "-c", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        livenessProbe: # Healthcheck สำหรับ Kafka
          exec:
            command: ["bash", "-c", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service # <<--- ชื่อ Service ที่ Clients (เช่น Kafdrop, NestJS) จะใช้เชื่อมต่อ
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext
      protocol: TCP
      port: 9092 # Port ที่ Service จะเปิดใน Cluster สำหรับ Clients
      targetPort: plaintext
    - name: plaintext-internal
      protocol: TCP
      port: 29092 # Port สำหรับการสื่อสารภายใน Broker
      targetPort: plaintext-internal
  type: ClusterIP