apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: default # ควรเป็น Namespace เดียวกันกับ App
data:
  APP_STAGE: "dev"
  REDIS_HOST: "redis-service" # <<--- เปลี่ยนเป็นชื่อ Service ของ Redis ใน K8s
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  JWT_ACCESS_DURATION: "86400"
  JWT_REFRESH_DURATION: "604800"
  JWT_API_DURATION: "31536000"