apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
  namespace: default
type: Opaque
data:
  # ค่าต้องเป็น Base64 Encoded (เช่น echo -n "secret_value" | base64)
  JWT_SECRET: <base64_encoded_value_of_JWT_SECRET>
  REDIS_PASSWORD: <base64_encoded_value_of_REDIS_PASSWORD> # ถ้าไม่มีรหัสผ่าน ให้ใช้ echo -n "" | base64
