import { Types } from 'mongoose';

export class CheckinLocation {
  description?: string;
  latitude?: number;
  longitude?: number;
}

export class Checkin {
  _id?: string | Types.ObjectId;
  
  // User who checked in
  user: string | Types.ObjectId;
  
  // Activity related to this checkin
  activity: string | Types.ObjectId;
  
  // Checkin timestamp
  scanTime: Date;
  
  // Server processing timestamp
  processedTime?: Date;
  
  // Status of the checkin
  status: 'pending' | 'success' | 'failed' | 'duplicate';
  
  // Boolean to indicate successful check-in
  isCheckedIn: boolean;
  
  // Additional notes
  notes?: string;
  
  // Checkin location data
  location?: CheckinLocation;
  
  // Staff who processed this checkin
  scannedBy?: string | Types.ObjectId;
  
  // Device ID for offline support
  deviceId?: string;
  
  // Local ID generated by the scanner device
  localId?: string;
  
  // Flag to indicate if this was processed offline and synced later
  isOfflineSync: boolean;
  
  // Custom fields for flexibility
  metadata?: Record<string, any>;
  
  // Timestamps
  createdAt?: Date;
  updatedAt?: Date;
}
