import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: 'transparent', marginTop: 36 },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: width * 0.045,
    marginTop: 0,
  },
  leaderboardTitle: {
    color: '#fff',
    fontSize: width * 0.032,
    letterSpacing: 2,
    fontWeight: '600',
  },
  leaderboardSubtitle: {
    color: '#fff',
    fontSize: width * 0.065,
    fontWeight: 'bold',
    letterSpacing: 2,
    marginTop: -2,
  },
  switchButton: { padding: width * 0.015 },
  switchIconWrap: {
    width: width * 0.095,
    height: width * 0.095,
    borderRadius: width * 0.0475,
    backgroundColor: 'rgba(255,255,255,0.13)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  switchIcon: { fontSize: width * 0.055 },
  top3Container: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: height * 0.022,
    marginTop: height * 0.05,
  },
  topUser: { alignItems: 'center', width: width * 0.225, position: 'relative' },
  topUserMain: { alignItems: 'center', width: width * 0.275, position: 'relative' },
  profileCircleInner: {
    width: width * 0.16,
    height: width * 0.16,
    borderRadius: width * 0.08,
    backgroundColor: '#ffffff70',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileCircleInnerMain: {
    width: width * 0.215,
    height: width * 0.215,
    borderRadius: width * 0.1075,
    backgroundColor: '#ffffff70',
    justifyContent: 'center',
    alignItems: 'center',
  },
  topAvatarEmoji: { fontSize: width * 0.09 },
  topAvatarMainEmoji: { fontSize: width * 0.12 },
  crownWrap: { position: 'absolute', top: -height * 0.05, left: width * 0.0625, zIndex: 2 },
  crownImage: {
    width: width * 0.15,
    height: width * 0.15,
    resizeMode: 'contain',
  },
  topRankCircle: {
    position: 'absolute',
    top: width * 0.11,
    left: width * 0.11,
    backgroundColor: '#fff',
    borderRadius: width * 0.0325,
    width: width * 0.065,
    height: width * 0.065,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#b6c3d1',
    zIndex: 2,
  },
  topRankText: { fontWeight: 'bold', color: '#222', fontSize: width * 0.04 },
  topName: {
    color: '#fff',
    fontWeight: 'bold',
    marginTop: 10,
    textAlign: 'center',
    fontSize: width * 0.0375,
  },
  topNameMain: {
    color: '#fff',
    fontWeight: 'bold',
    marginTop: 18,
    fontSize: width * 0.045,
    textAlign: 'center',
  },
  topSteps: {
    color: '#b6c3d1',
    fontSize: width * 0.0325,
    textAlign: 'center',
    fontWeight: '600',
  },
  topStepsMain: {
    color: '#b6c3d1',
    fontSize: width * 0.0375,
    textAlign: 'center',
    fontWeight: '600',
  },
  underline: {
    width: width * 0.135,
    height: 2,
    backgroundColor: '#b6c3d1',
    alignSelf: 'center',
    marginTop: 2,
    marginBottom: 2,
    borderRadius: 1,
  },
  underlineMain: {
    width: width * 0.175,
    height: 3,
    backgroundColor: '#b6c3d1',
    alignSelf: 'center',
    marginTop: 4,
    marginBottom: 2,
    borderRadius: 1.5,
  },
  listContainer: { paddingHorizontal: width * 0.025 },
  cardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: width * 0.045,
    marginVertical: height * 0.007,
    padding: width * 0.03,
    paddingLeft: width * 0.045,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  cardMyteam: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderRadius: width * 0.045,
    marginVertical: height * 0.007,
    marginBottom: height * 0.06,
    padding: width * 0.03,
    paddingLeft: width * 0.045,
    shadowColor: '#333',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 10,
  },
  cardRankCircle: {
    width: width * 0.08,
    height: width * 0.08,
    borderRadius: width * 0.04,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: width * 0.025,
  },
  cardRankText: {
    fontWeight: 'bold',
    color: '#fff',
    fontSize: width * 0.04,
  },
  cardAvatar: {
    width: width * 0.09,
    height: width * 0.09,
    borderRadius: width * 0.045,
    backgroundColor: '#fff',
    marginRight: width * 0.035,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#b6c3d1',
  },
  cardMyAvatar: {
    width: width * 0.09,
    height: width * 0.09,
    borderRadius: width * 0.045,
    backgroundColor: '#fff',
    marginRight: width * 0.035,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#b6c3d1',
    position: 'relative',
  },
  cardAvatarEmoji: { fontSize: width * 0.055 },
  cardName: { color: '#fff', fontWeight: 'bold', flex: 1, fontSize: width * 0.0375 },
  cardMyName: { color: '#fff', fontWeight: 'bold', flex: 1, fontSize: width * 0.04 },
  cardSteps: { color: '#b6c3d1', fontWeight: 'bold', fontSize: width * 0.0375 },
  cardMySteps: { color: '#fff', fontWeight: 'bold', fontSize: width * 0.0375 },
  rankNumberCircle1: {
    position: 'absolute',
    bottom: -18,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    alignSelf: 'center',
  },
  rankNumberCircle2: {
    position: 'absolute',
    bottom: -14,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    alignSelf: 'center',
  },
  rankNumberCircle3: {
    position: 'absolute',
    bottom: -14,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    alignSelf: 'center',
  },
  rankNumberText: {
    fontWeight: 'bold',
    color: '#fff',
    fontSize: 18,
  },
  rankNumberTextMain: {
    fontWeight: 'bold',
    color: '#fff',
    fontSize: 24,
  },
  glassProfileCircleOuter: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: 'rgba(255,255,255,0.13)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    marginBottom: 4,
    position: 'relative',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.35)',
    overflow: 'hidden',
  },
  glassProfileCircleOuterMain: {
    width: 98,
    height: 98,
    borderRadius: 49,
    backgroundColor: 'rgba(255,255,255,0.18)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    marginBottom: 4,
    marginTop: -18,
    position: 'relative',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.45)',
    overflow: 'hidden',
  },
  switchOvalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 32,
    borderWidth: 2,
    borderColor: '#fff',
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 18,
    height: 48,
  },
  cardContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: height * 0.022,
    marginTop: height * 0.13,
  },
  avatarFallback: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ccc',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  avatarInitials: {
    fontWeight: 'bold',
    color: 'white',
  },

});

export default styles;