import { Type } from "class-transformer";
import { 
  IsBoolean,
  IsDateString, 
  IsEnum, 
  IsMongoId, 
  IsNotEmpty, 
  IsNumber, 
  IsObject, 
  IsOptional, 
  IsString, 
  ValidateNested 
} from "class-validator";
import { Types } from "mongoose";

export class CheckinLocationDto {
  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsNumber()
  latitude?: number;

  @IsOptional()
  @IsNumber()
  longitude?: number;
}

export class CreateCheckinDto {
  // User who checked in (from QR code or manual entry)
  @IsNotEmpty()
  @IsMongoId()
  user: string | Types.ObjectId;

  // Activity related to this checkin
  @IsNotEmpty()
  @IsMongoId()
  activity: string | Types.ObjectId;

  // Scan timestamp
  @IsOptional()
  @IsDateString()
  scanTime?: string;

  // Boolean to indicate successful check-in
  @IsOptional()
  @IsBoolean()
  isCheckedIn?: boolean;

  // Status of the checkin
  @IsOptional()
  @IsEnum(['pending', 'success', 'failed', 'duplicate'])
  status?: string;

  // Additional notes
  @IsOptional()
  @IsString()
  notes?: string;

  // Checkin location data
  @IsOptional()
  @ValidateNested()
  @Type(() => CheckinLocationDto)
  location?: CheckinLocationDto;

  // Staff who scanned this check-in
  @IsNotEmpty()
  @IsMongoId()
  scannedBy: string | Types.ObjectId;

  // Device ID for offline support
  @IsOptional()
  @IsString()
  deviceId?: string;

  // Local ID generated by the scanner device
  @IsOptional()
  @IsString()
  localId?: string;

  // Flag to indicate if this was processed offline and synced later
  @IsOptional()
  @IsBoolean()
  isOfflineSync?: boolean;

  // Custom fields for flexibility
  @IsOptional()
  @IsObject()
  metadata?: Record<string, any>;
}
